# Generated by Django 6.0.3 on 2026-04-09 01:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PuntoCosta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del punto o ubicación', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción o detalles relevantes', null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(help_text='Coordenadas exactas en la línea de costa', srid=4326)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Punto de Costa',
                'verbose_name_plural': 'Puntos de Costa',
            },
        ),
        migrations.CreateModel(
            name='FotoPunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='fotos_costa/')),
                ('leyenda', models.CharField(blank=True, help_text='Pie de foto opcional', max_length=255, null=True)),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('punto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='mapapp.puntocosta')),
            ],
        ),
    ]
