# Generated by Django 6.0.3 on 2026-05-09 18:45

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPlayas',
            fields=[
                ('id', models.CharField(primary_key=True, serialize=False)),
                ('nombre_tramo', models.CharField(blank=True, null=True)),
                ('coord_init', models.CharField(blank=True, null=True)),
                ('coord_final', models.CharField(blank=True, null=True)),
                ('long', models.CharField(blank=True, null=True)),
                ('tipo_geomorfo', models.CharField(blank=True, null=True)),
                ('subtipo_detallado', models.CharField(blank=True, null=True)),
                ('tipo_playa', models.CharField(blank=True, null=True)),
                ('nivel_energia', models.CharField(blank=True, null=True)),
                ('dir_dominante', models.CharField(blank=True, null=True)),
                ('mag_estimada', models.CharField(blank=True, null=True)),
                ('fuentes_sedimento', models.CharField(blank=True, null=True)),
                ('sumideros_sedimento', models.CharField(blank=True, null=True)),
                ('balance_sedimentario', models.CharField(blank=True, null=True)),
                ('est_costeras', models.CharField(blank=True, null=True)),
                ('ev_erosion', models.CharField(blank=True, null=True)),
                ('influ_arrecifal', models.CharField(blank=True, null=True)),
                ('influ_manglar', models.CharField(blank=True, null=True)),
                ('pres_antropic', models.CharField(blank=True, null=True)),
                ('conectividad', models.CharField(blank=True, null=True)),
                ('incertidumbre', models.CharField(blank=True, null=True)),
                ('tipo_soporte', models.CharField(blank=True, null=True)),
                ('geom_init', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'datos_playas',
                'managed': False,
            },
        ),
    ]
